#include "devmgr/app/modules_vm.hpp"

#include <algorithm>
#include <array>
#include <cctype>  // CONTROLLER AMENDMENT (D-5): tolower
#include <chrono>  // FIX ROUND 1 (i-1): wait_for coalescing check
#include <cstdint>
#include <cstdio>
#include <utility>

#include "devmgr/core/events.hpp"

namespace devmgr::app {
namespace {

// CONTROLLER AMENDMENT (D-9): shared helper instead of the two
// std::transform(..., ::tolower) call sites the plan specified — identical
// behavior for ASCII, and it removes real UB from passing a (possibly
// negative) plain `char` to ::tolower.
std::string toLowerCopy(std::string s) {
    std::ranges::transform(s, s.begin(),
                           [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    return s;
}

// Comma-joined module holders, truncated to the fixed column width.
std::string joinHolders(const std::vector<std::string>& holders) {
    std::string joined;
    for (const auto& h : holders) {
        if (!joined.empty()) joined += ",";
        joined += h;
    }
    static constexpr std::size_t kHoldersMaxLen = 24;
    static constexpr std::size_t kHoldersTruncatedLen = 21;
    if (joined.size() > kHoldersMaxLen) joined = joined.substr(0, kHoldersTruncatedLen) + "…";
    return joined;
}

// UTF-8 continuation bytes are 10xxxxxx; every other byte begins a codepoint.
constexpr unsigned char kUtf8ContinuationMask = 0xC0U;
constexpr unsigned char kUtf8ContinuationBits = 0x80U;

bool isContinuationByte(unsigned char c) {
    return (c & kUtf8ContinuationMask) == kUtf8ContinuationBits;
}

// Display width in terminal columns. Module names, signer names and the numeric
// cells are single-byte; the only multi-byte glyph these rows carry is the "…"
// ellipsis (three bytes, one column). Counting UTF-8 lead bytes is therefore
// exact here — and printf's byte-based `%-Ns` padding is not, which is why the
// signature cell is padded by hand below.
std::size_t displayWidth(std::string_view s) {
    std::size_t w = 0;
    for (const unsigned char c : s) {
        if (!isContinuationByte(c)) ++w;
    }
    return w;
}

// Drops the last whole codepoint (never half of a multi-byte sequence).
void popCodepoint(std::string& s) {
    if (s.empty()) return;
    s.pop_back();
    while (!s.empty() && isContinuationByte(static_cast<unsigned char>(s.back()))) s.pop_back();
}

// `cell` normalised to exactly `cols` display columns: padded with spaces, or
// ellipsis-truncated when it is wider. Keeps every column to the right of it in
// place — including while the async signature fill still shows "…".
std::string padTo(std::string cell, std::size_t cols) {
    if (displayWidth(cell) > cols) {
        while (displayWidth(cell) > cols - 1) popCodepoint(cell);
        cell += "…";
    }
    cell.append(cols - displayWidth(cell), ' ');
    return cell;
}

// Row cells, named so the two strings cannot be passed the wrong way round.
struct ModuleRowCells {
    std::string signature;  // "yes (signer)" | "yes" | "NO" | "?" | "…" (pending)
    std::string holders;    // comma-joined, already width-truncated
};

// Fixed-column module row (shared byte-for-byte with T11/T12 and with the GUI's
// ModuleListModel; the emitted format — NOT the brief prose — is authoritative
// per CONTROLLER AMENDMENT D-6).
//
// Column order is Name, Signed, Ref, Size, Used-by (pass-2 bug B5). Signed moved
// from last to second: it is what the user scans this list for, and at 80
// columns the row is clipped from the right, so the old order dropped the
// signature first and kept Used-by — exactly backwards. Used-by is now the
// widest, least load-bearing cell and the first to go.
std::string formatModuleRow(const core::LoadedModule& m, const ModuleRowCells& cells) {
    static constexpr std::size_t kRowBufferSize = 128;
    static constexpr std::uint64_t kBytesPerKb = 1024;
    // A signer name can be arbitrarily long ("yes (Build time autogenerated
    // kernel key)"); capped here so it cannot push Ref/Size/Used-by out of
    // alignment now that it is no longer the last cell. The detail pane carries
    // the full string. 20 is what the 80-column budget allows: the list pane is
    // 72 wide, leaving ~67 usable after the border, the "> " marker and the
    // scroll affordance, and Name(28)+1+Signed(20)+1+Ref(4)+1+Size(8)+2 = 65 —
    // so Name, Signed, Ref and Size all survive at 80 columns and Used-by is the
    // cell that clips.
    static constexpr std::size_t kSignedCols = 20;
    const std::string signedCell = padTo(cells.signature, kSignedCols);
    std::array<char, kRowBufferSize> row{};
    // snprintf is the only practical way to reproduce the fixed printf-style
    // column alignment shared byte-for-byte with T11/T12.
    // NOLINTNEXTLINE(cppcoreguidelines-pro-type-vararg)
    std::snprintf(row.data(), row.size(), "%-28s %s %4ld %7lluK  %s", m.name.c_str(),
                  signedCell.c_str(), m.refCount,
                  static_cast<unsigned long long>(m.sizeBytes / kBytesPerKb),
                  cells.holders.c_str());
    return {row.data()};
}

// "yes (signer)" | "yes" | "NO" for a resolved driver. The parenthesised signer
// appears only when there is one to name (pass-2 bug B5): a present-but-empty
// signer field rendered as the meaningless "yes ()".
std::string signatureLabel(const core::Driver& d) {
    if (!d.isSigned) return "NO";
    if (const auto& signer = d.signer; signer && !signer->empty()) return "yes (" + *signer + ")";
    return "yes";
}

// Signature-cell text for the row column: "?" when the module could not be
// classified, otherwise signatureLabel().
std::string signatureCellFor(const core::Result<core::Driver>& info) {
    return info ? signatureLabel(*info) : std::string("?");
}

// Maps the signature-column cell text to a colouring state (design decision
// 1a). "NO" → Unsigned, a "yes…" cell → Signed; "?" (unclassifiable) and "…"
// (async pending) both → Undetermined. Kept next to signatureCellFor() so the
// two agree on what the cell strings mean.
ModuleSignature classifySignatureCell(const std::string& cell) {
    if (cell == "NO") return ModuleSignature::Unsigned;
    if (cell.starts_with("yes")) return ModuleSignature::Signed;
    return ModuleSignature::Undetermined;
}

// Restores the highlighted module by name after a rebuild, then clamps.
int restoreSelection(const std::vector<std::optional<std::string>>& rowNames,
                     const std::optional<std::string>& keep, int current, int rowCount) {
    if (keep) {
        if (auto it = std::ranges::find(rowNames, keep); it != rowNames.end())
            current = static_cast<int>(std::distance(rowNames.begin(), it));
    }
    return std::clamp(current, 0, rowCount - 1);
}

void appendModuleInfo(std::vector<std::string>& out, const core::Result<core::Driver>& info) {
    if (!info) return;
    if (!info->version.empty()) out.push_back("Version: " + info->version);
    if (!info->path.empty()) out.push_back("Path:    " + info->path);
    out.push_back("Signed:  " + signatureLabel(*info));
    if (info->dependencies.empty()) return;
    std::string deps;
    for (const auto& d : info->dependencies) {
        if (!deps.empty()) deps += ", ";
        deps += d;
    }
    out.push_back("Depends: " + deps);
}

void appendModprobeInfo(std::vector<std::string>& out, const core::Result<core::ModprobeInfo>& mp) {
    if (!mp) return;
    if (const auto& options = mp->options) out.push_back("Options: " + *options);
    if (mp->blacklisted) out.emplace_back("modprobe.d: blacklisted");
}

}  // namespace

ModulesVM::ModulesVM(ApplicationFacade& facade, runtime::EventBus& bus,
                     runtime::TaskScheduler& scheduler, IUiDispatcher& dispatcher)
    : facade_(facade), bus_(bus), scheduler_(scheduler), dispatcher_(dispatcher) {
    subModules_ = bus_.subscribe<core::ModulesChangedEvent>(
        [this](const core::ModulesChangedEvent&) { onModulesChanged(); });
}

ModulesVM::~ModulesVM() {
    // FIX ROUND 1 (i-2): clear the alive token BEFORE waiting. Any closure
    // already posted to a queuing dispatcher (FTXUI/Qt in T11/T12) checks
    // this and no-ops instead of touching a dead VM. Safe without a mutex:
    // the destructor and IUiDispatcher::post()'s execution both happen on the
    // UI thread and therefore serialize.
    alive_->store(false);
    // The worker lambda submitted to scheduler_ still captures `this`
    // directly (for facade_/dispatcher_/scheduler_) and is NOT alive_-token
    // guarded, so this wait must remain: it is the only thing that keeps
    // that worker's `this` access memory-safe.
    if (sigFill_.valid()) sigFill_.wait();
}

void ModulesVM::onModulesChanged() {
    if (rebuildQueued_.exchange(true)) return;  // coalesce bursts
    auto alive = alive_;
    dispatcher_.post([this, alive] {
        if (!alive->load()) return;  // FIX ROUND 1 (i-2): VM died before this ran
        rebuildQueued_.store(false);
        rebuild();
    });
}

void ModulesVM::setFilter(std::string filter) {
    filter_ = toLowerCopy(std::move(filter));
    rebuild();
}

void ModulesVM::setRebuildHooks(std::function<void()> before, std::function<void()> after) {
    beforeRebuild_ = std::move(before);
    afterRebuild_ = std::move(after);
}

// Which "nothing here" the empty list actually is — the SnapshotsVM shape,
// applied to this view. Four distinct truths, never conflated:
//
//   no source implemented -> the unsupported sentence, in place of the content:
//                            no query ran and none can, so neither an
//                            empty-result nor a filter string would be true
//   a filter hid it       -> "(no matches)", true whether or not a source is up
//   the daemon answered   -> "(no modules)", a completed query
//   the daemon never did  -> NO row: the banner's shared sentence explains the
//                            empty region instead (docs/DESIGN.md §6.1)
void ModulesVM::pushEmptyStateRow() {
    if (const auto unsupported = unsupportedContent()) {
        rows_.push_back(*unsupported);
    } else if (!filter_.empty()) {
        rows_.emplace_back("(no matches)");
    } else if (!facade_.daemonAvailability()) {
        rows_.emplace_back("(no modules)");
    } else {
        return;
    }
    rowNames_.emplace_back(std::nullopt);
}

void ModulesVM::rebuild() {
    if (beforeRebuild_) beforeRebuild_();
    const auto keep = selectedModule();
    auto loaded = facade_.listModules();
    snapshot_ = loaded ? std::move(*loaded) : std::vector<core::LoadedModule>{};
    std::ranges::sort(snapshot_, {}, &core::LoadedModule::name);
    rows_.clear();
    rowNames_.clear();
    for (const auto& m : snapshot_) {
        const std::string haystack = toLowerCopy(m.name);
        if (!filter_.empty() && haystack.find(filter_) == std::string::npos) continue;
        const auto sig = signatureCell_.find(m.name);
        rows_.push_back(
            formatModuleRow(m, {.signature = sig != signatureCell_.end() ? sig->second : "…",
                                .holders = joinHolders(m.holders)}));
        rowNames_.emplace_back(m.name);
    }
    if (rows_.empty()) pushEmptyStateRow();
    // A withheld empty-state row can leave the list genuinely empty, and
    // restoreSelection clamps into [0, rowCount-1] — an empty range. Guard it
    // here, as UpdatesVM and SnapshotsVM already do for the same reason.
    selected_ = rows_.empty()
                    ? 0
                    : restoreSelection(rowNames_, keep, selected_, static_cast<int>(rows_.size()));
    if (afterRebuild_) afterRebuild_();
}

std::optional<std::string> ModulesVM::selectedModule() const {
    if (selected_ < 0 || std::cmp_greater_equal(selected_, rowNames_.size())) return std::nullopt;
    return rowNames_[static_cast<std::size_t>(selected_)];
}

std::optional<ModuleSignature> ModulesVM::signedForRow(int row) const {
    if (row < 0 || std::cmp_greater_equal(row, rowNames_.size())) return std::nullopt;
    const auto& name = rowNames_[static_cast<std::size_t>(row)];
    if (!name) return std::nullopt;  // placeholder row carries no module
    const auto it = signatureCell_.find(*name);
    return classifySignatureCell(it != signatureCell_.end() ? it->second : std::string("…"));
}

std::optional<core::Criticality> ModulesVM::criticalityForRow(int row) const {
    if (row < 0 || std::cmp_greater_equal(row, rowNames_.size())) return std::nullopt;
    const auto& name = rowNames_[static_cast<std::size_t>(row)];
    if (!name) return std::nullopt;  // placeholder row carries no module
    // Classify from the snapshot entry the row was formatted from, so the
    // marker and the Ref/Used-by columns can never describe different states.
    const auto it = std::ranges::find(snapshot_, *name, &core::LoadedModule::name);
    if (it == snapshot_.end()) return core::Criticality::Ordinary;
    return core::classifyModule(it->name, it->refCount, it->holders);
}

std::shared_future<void> ModulesVM::fillSignatures() {
    // FIX ROUND 1 (i-1 sub-issue), coalescing option (a): if a fill is
    // already in flight (valid and not yet ready), return that handle
    // instead of starting a second overlapping worker. This keeps the
    // invariant that sigFill_ always names the SOLE outstanding worker, so
    // the destructor's sigFill_.wait() always waits for it — the worker
    // lambda captures `this` directly and is not alive_-token guarded (see
    // dtor), so that invariant is what keeps it memory-safe. It also avoids
    // redundant duplicate facade_.moduleDetail() calls for names already
    // being classified by the in-flight worker.
    if (sigFill_.valid() && sigFill_.wait_for(std::chrono::seconds(0)) != std::future_status::ready)
        return sigFill_;

    // Snapshot the UNCACHED names on the caller (UI) thread (spec §7.1 perf:
    // re-entering the view never re-reads .ko files already classified); the
    // worker only touches the facade + a local map, then posts the merge back.
    std::vector<std::string> names;
    for (const auto& m : snapshot_)
        if (!signatureCell_.contains(m.name)) names.push_back(m.name);
    if (names.empty()) {
        // FIX ROUND 1 (i-1): produce an already-ready future rather than
        // returning a possibly-default-constructed (invalid) sigFill_. This
        // is exactly the class's own designed happy path (spec §7.1):
        // re-entering the view when every signature is already cached.
        std::promise<void> ready;
        ready.set_value();
        sigFill_ = ready.get_future().share();
        return sigFill_;
    }
    auto alive = alive_;
    sigFill_ = scheduler_
                   .submit([this, names = std::move(names), alive] {
                       std::map<std::string, std::string> cells;
                       for (const auto& name : names)
                           cells[name] = signatureCellFor(facade_.moduleDetail(name));
                       dispatcher_.post([this, alive, cells = std::move(cells)]() mutable {
                           if (!alive->load()) return;  // FIX ROUND 1 (i-2): VM already dead
                           for (auto& [k, v] : cells) signatureCell_[k] = std::move(v);
                           rebuild();
                       });
                   })
                   .share();
    return sigFill_;
}

std::string ModulesVM::columnHeader() const {
    // Built from the SAME widths formatModuleRow() uses, so the header can never
    // drift out of alignment with the rows beneath it (R5). Ref and Size are
    // right-aligned because their values are.
    static constexpr std::size_t kRowBufferSize = 128;
    std::array<char, kRowBufferSize> row{};
    // NOLINTNEXTLINE(cppcoreguidelines-pro-type-vararg)
    std::snprintf(row.data(), row.size(), "%-28s %-20s %4s %8s  %s", "Name", "Signed", "Ref",
                  "Size", "Used-by");
    return {row.data()};
}

std::vector<BackendNote> ModulesVM::availabilityNotes() const {
    const auto note = facade_.backendStatus().noteFor(core::BackendId::Devmgrd);
    if (!note) return {};
    return {*note};
}

// This view has exactly two sources: the module list, read locally through
// IDriverManager, and the load/unload verbs, which run through the privileged
// channel. With neither implemented there is nothing here to report and nothing
// to do, so the sentence replaces the list rather than an empty region
// appearing under a banner.
std::optional<std::string> ModulesVM::unsupportedContent() const {
    const auto caps = facade_.capabilities();
    return unsupportedViewText(core::BackendId::Devmgrd,
                               !caps.driverManagement && !caps.privilegedChannel);
}

BannerLine ModulesVM::bannerLine() const {
    // The degraded sentence leads and raises the row's valence to at most the
    // note's own role; the Secure Boot posture follows it. One banner row, one
    // severity, both facts — the Snapshots composition, applied to this banner.
    const auto notes = availabilityNotes();
    const auto withNote = [&notes](BannerLine line) {
        if (notes.empty()) return line;
        line.text = notes.front().text + " | " + line.text;
        // The note's OWN role decides whether the row rises, not the mere fact
        // that a note exists: an unsupported backend is information under every
        // input (backend-availability, "Unsupported never escalates"), so
        // prepending its sentence must not raise the row. Raising only — a
        // Secure Boot warning already on this line is never demoted by a calmer
        // note joining it. (StatusSeverity is not ordered by severity, so this
        // is a test, not a max().)
        if (notes.front().role == StatusSeverity::Warning) line.severity = StatusSeverity::Warning;
        return line;
    };
    const auto info = facade_.systemInfo();
    if (!info) return withNote({.text = "Secure Boot: unknown", .severity = StatusSeverity::Info});
    // ONE predicate decides both the sentence and its valence: the posture that
    // makes an unsigned load fail is the same posture that is worth a warning.
    // Reading it once here is what retires the render-path substring match — the
    // surface can no longer disagree with the VM about which state it is in.
    // An undeterminable Secure Boot state is "unknown", never "off": reporting
    // it off would tell the user unsigned modules load, on the strength of a
    // read that failed.
    const bool rejectsUnsigned = info->secureBoot.value_or(false) || info->lockdownMode != "none";
    const char* state = !info->secureBoot ? "unknown" : (*info->secureBoot ? "ON" : "off");
    std::string text = std::string("Secure Boot: ") + state + " · Lockdown: " + info->lockdownMode;
    if (rejectsUnsigned) text += " — unsigned modules will be rejected";
    return withNote({.text = std::move(text),
                     .severity = rejectsUnsigned ? StatusSeverity::Warning : StatusSeverity::Info});
}

std::string ModulesVM::banner() const {
    return bannerLine().text;
}

std::vector<std::string> ModulesVM::detailLines() const {
    const auto name = selectedModule();
    if (!name) return {"(no module selected)"};
    std::vector<std::string> out;
    out.push_back("Module:  " + *name);
    // R4: the row shows a criticality MARKER; the word and the risk it names
    // belong here, so the marker never has to carry its meaning alone. Read from
    // the same snapshot entry the row was formatted from (criticalityForRow), so
    // the two can never describe different modules.
    if (const auto level = criticalityForRow(selected_);
        level && *level != core::Criticality::Ordinary) {
        out.push_back(std::string("Risk:    ") + core::displayCriticality(*level) + " — " +
                      (*level == core::Criticality::Essential
                           ? "unloading this may make the system unusable"
                           : "in use or security-enforcing; unloading will be felt"));
    }
    appendModuleInfo(out, facade_.moduleDetail(*name));
    appendModprobeInfo(out, facade_.modprobeDetail(*name));
    return out;
}

}  // namespace devmgr::app
